stages:
  data_ingestion:
    cmd: python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
      - /Users/atatekeli/PycharmProjects/coccidiosis-classifier/config/config.yaml
    outs:
      - artifacts/data_ingestion/CoccidiosisDataset
