stages:
  data_ingestion:
    cmd: python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
      - /Users/atatekeli/PycharmProjects/coccidiosis-classifier/config/config.yaml
    outs:
      - artifacts/data_ingestion/Coccidiosis Dataset

  prepare_base_model:
    cmd: python src/CoccidiosisClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CoccidiosisClassifier/pipeline/stage_02_prepare_base_model.py
      - /Users/atatekeli/PycharmProjects/coccidiosis-classifier/config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/CoccidiosisClassifier/pipeline/stage_03_training.py
    deps:
      - src/CoccidiosisClassifier/pipeline/stage_03_training.py
      - src/CoccidiosisClassifier/components/prepare_callback.py
      - /Users/atatekeli/PycharmProjects/coccidiosis-classifier/config/config.yaml
      - artifacts/data_ingestion/Coccidiosis Dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/CoccidiosisClassifier/pipeline/stage_04_evaluation.py
    deps:
      - src/CoccidiosisClassifier/pipeline/stage_04_evaluation.py
      - /Users/atatekeli/PycharmProjects/coccidiosis-classifier/config/config.yaml
      - artifacts/data_ingestion/Coccidiosis Dataset
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
