from src.CoccidiosisClassifier.config.configuration import ConfigurationManager
from src.CoccidiosisClassifier.components.data_ingestion import DataIngestion
from src.CoccidiosisClassifier import logger
