artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Killpit/coccidiosis-classifier/raw/main/Coccidiosis%20Dataset.zip
  local_data_file: artifacts/data_ingestion/coccidiosisdata.zip
  unzip_dir: artifacts/data_ingestion